"""fase 3 unified movements models

Revision ID: 0e55e969c04a
Revises: 54b98900e41e
Create Date: 2026-04-30 18:54:15.616512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e55e969c04a'
down_revision: Union[str, Sequence[str], None] = '54b98900e41e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=True)
    op.create_table('periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sheet_id', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_period_year_month')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='app', nullable=False),
    sa.Column('sheet_id', sa.String(length=255), nullable=True),
    sa.Column('sheet_tab', sa.String(length=120), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.CheckConstraint("source IN ('app', 'sheet')", name='ck_movements_source'),
    sa.CheckConstraint("type IN ('compra', 'venta', 'gasto', 'pago', 'sueldo')", name='ck_movements_type'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_client_id'), 'movements', ['client_id'], unique=False)
    op.create_index(op.f('ix_movements_date'), 'movements', ['date'], unique=False)
    op.create_index(op.f('ix_movements_employee_id'), 'movements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_movements_period_id'), 'movements', ['period_id'], unique=False)
    op.create_index(op.f('ix_movements_type'), 'movements', ['type'], unique=False)
    op.create_table('movement_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("type IN ('producto', 'empleado', 'gasto')", name='ck_movement_details_type'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_details_employee_id'), 'movement_details', ['employee_id'], unique=False)
    op.create_index(op.f('ix_movement_details_movement_id'), 'movement_details', ['movement_id'], unique=False)
    op.create_index(op.f('ix_movement_details_product_id'), 'movement_details', ['product_id'], unique=False)
    op.create_index(op.f('ix_movement_details_type'), 'movement_details', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movement_details_type'), table_name='movement_details')
    op.drop_index(op.f('ix_movement_details_product_id'), table_name='movement_details')
    op.drop_index(op.f('ix_movement_details_movement_id'), table_name='movement_details')
    op.drop_index(op.f('ix_movement_details_employee_id'), table_name='movement_details')
    op.drop_table('movement_details')
    op.drop_index(op.f('ix_movements_type'), table_name='movements')
    op.drop_index(op.f('ix_movements_period_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_employee_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_date'), table_name='movements')
    op.drop_index(op.f('ix_movements_client_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_table('periods')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
