"""add prices table

Revision ID: 4b3cb42af105
Revises: 0e55e969c04a
Create Date: 2026-05-01 13:05:25.557123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3cb42af105'
down_revision: Union[str, Sequence[str], None] = '0e55e969c04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'product', 'start_date', name='uq_prices_client_product_start_date')
    )
    op.create_index('ix_prices_client_product_start_date', 'prices', ['client_id', 'product', 'start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_client_product_start_date', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
