"""init

Revision ID: 760c28f713f8
Revises: 
Create Date: 2026-05-02 02:44:04.494775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760c28f713f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    op.create_index('uq_clients_name_ci', 'clients', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_name', 'employees', ['name'], unique=False)
    op.create_index('uq_employees_name_ci', 'employees', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('movements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('COMPRA', 'VENTA', 'GASTO', 'SUELDO', 'ENTREGA_DINERO', 'PAGO_CLIENTE', name='movement_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_date'), 'movements', ['date'], unique=False)
    op.create_index(op.f('ix_movements_period_id'), 'movements', ['period_id'], unique=False)
    op.create_index(op.f('ix_movements_type'), 'movements', ['type'], unique=False)
    op.create_table('periods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sheet_id', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_period_year_month')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.create_index('uq_products_name_ci', 'products', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('movement_client_payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_client_payments_client_id'), 'movement_client_payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_movement_client_payments_movement_id'), 'movement_client_payments', ['movement_id'], unique=False)
    op.create_table('movement_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_items_client_id'), 'movement_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_movement_items_movement_id'), 'movement_items', ['movement_id'], unique=False)
    op.create_index(op.f('ix_movement_items_product_id'), 'movement_items', ['product_id'], unique=False)
    op.create_table('movement_salaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_salaries_employee_id'), 'movement_salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_movement_salaries_movement_id'), 'movement_salaries', ['movement_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'product_id', 'start_date', name='uq_prices_client_product_start_date')
    )
    op.create_index('ix_prices_client_product_start_date', 'prices', ['client_id', 'product_id', 'start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_client_product_start_date', table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_movement_salaries_movement_id'), table_name='movement_salaries')
    op.drop_index(op.f('ix_movement_salaries_employee_id'), table_name='movement_salaries')
    op.drop_table('movement_salaries')
    op.drop_index(op.f('ix_movement_items_product_id'), table_name='movement_items')
    op.drop_index(op.f('ix_movement_items_movement_id'), table_name='movement_items')
    op.drop_index(op.f('ix_movement_items_client_id'), table_name='movement_items')
    op.drop_table('movement_items')
    op.drop_index(op.f('ix_movement_client_payments_movement_id'), table_name='movement_client_payments')
    op.drop_index(op.f('ix_movement_client_payments_client_id'), table_name='movement_client_payments')
    op.drop_table('movement_client_payments')
    op.drop_index('uq_products_name_ci', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_table('products')
    op.drop_table('periods')
    op.drop_index(op.f('ix_movements_type'), table_name='movements')
    op.drop_index(op.f('ix_movements_period_id'), table_name='movements')
    op.drop_index(op.f('ix_movements_date'), table_name='movements')
    op.drop_table('movements')
    op.drop_index('uq_employees_name_ci', table_name='employees')
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_table('employees')
    op.drop_index('uq_clients_name_ci', table_name='clients')
    op.drop_index('ix_clients_name', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
